webtalk_init -webtalk_dir /home/daniel/work/elements-sdk/zibal/eda/Xilinx/syn/xsim.dir/TH294_top_func/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 22 21:11:23 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3ab5a26f-3fa8-481f-954b-7be8514ffd22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6cd9b8bd-c080-4bbb-85a1-a6d47077f4d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4772.687 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1346945 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "23.83_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116636_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1265578818 -regid "" -xml /home/daniel/work/elements-sdk/zibal/eda/Xilinx/syn/xsim.dir/TH294_top_func/webtalk/usage_statistics_ext_xsim.xml -html /home/daniel/work/elements-sdk/zibal/eda/Xilinx/syn/xsim.dir/TH294_top_func/webtalk/usage_statistics_ext_xsim.html -wdm /home/daniel/work/elements-sdk/zibal/eda/Xilinx/syn/xsim.dir/TH294_top_func/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
