# Board Constraints file for DH-008

## Clock Constraints
# Main clock with 100MHz
create_clock -name sys_clk_pin -period 10.0 [get_ports {io_clock}];
# JTAG clock with 10MHz
create_clock -name jtag_clk_pin -period 100.0 [get_ports {io_jtag_tck}];
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {io_jtag_tck_IBUF}]

## Clock
set_property PACKAGE_PIN E12 [get_ports {io_clock}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_clock}]

## Status
set_property PACKAGE_PIN K12 [get_ports {io_gpioStatus[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioStatus[0]}]
set_property PACKAGE_PIN L13 [get_ports {io_gpioStatus[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioStatus[1]}]
set_property PACKAGE_PIN K13 [get_ports {io_gpioStatus[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioStatus[2]}]
set_property PACKAGE_PIN G11 [get_ports {io_gpioStatus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioStatus[3]}]

## Stdout
set_property PACKAGE_PIN M4 [get_ports {io_uartStd_txd}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_uartStd_txd}]
set_property PACKAGE_PIN L4 [get_ports {io_uartStd_rxd}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_uartStd_rxd}]
set_property PACKAGE_PIN M2 [get_ports {io_uartStd_rts}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_uartStd_rts}]
set_property PACKAGE_PIN M1 [get_ports {io_uartStd_cts}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_uartStd_cts}]

## JTAG
set_property PACKAGE_PIN R13 [get_ports {io_jtag_tms}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_jtag_tms}]
set_property PACKAGE_PIN N13 [get_ports {io_jtag_tdi}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_jtag_tdi}]
set_property PACKAGE_PIN P13 [get_ports {io_jtag_tdo}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_jtag_tdo}]
set_property PACKAGE_PIN N14 [get_ports {io_jtag_tck}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_jtag_tck}]

## SPI FLASH
set_property PACKAGE_PIN N11 [get_ports {io_spi0_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_sclk}]
set_property PACKAGE_PIN M6 [get_ports {io_spi0_ss}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_ss}]
set_property PACKAGE_PIN N6 [get_ports {io_spi0_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_rst}]
set_property PACKAGE_PIN N9 [get_ports {io_spi0_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_mosi}]
set_property PACKAGE_PIN P9 [get_ports {io_spi0_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_miso}]
set_property PACKAGE_PIN P8 [get_ports {io_spi0_wp}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_wp}]
set_property PACKAGE_PIN R8 [get_ports {io_spi0_hold}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_spi0_hold}]

## CONTROLLER

set_property PACKAGE_PIN F2  [get_ports {io_gpioController[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[0]}]
set_property PACKAGE_PIN E1  [get_ports {io_gpioController[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[1]}]
set_property PACKAGE_PIN G5  [get_ports {io_gpioController[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[2]}]
set_property PACKAGE_PIN G4  [get_ports {io_gpioController[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[3]}]
set_property PACKAGE_PIN G1  [get_ports {io_gpioController[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[4]}]
set_property PACKAGE_PIN G2  [get_ports {io_gpioController[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[5]}]
set_property PACKAGE_PIN T15 [get_ports {io_gpioController[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[6]}]
set_property PACKAGE_PIN R15 [get_ports {io_gpioController[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[7]}]
set_property PACKAGE_PIN L5  [get_ports {io_gpioController[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[8]}]
set_property PACKAGE_PIN T14 [get_ports {io_gpioController[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[9]}]
set_property PACKAGE_PIN R10 [get_ports {io_gpioController[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[10]}]
set_property PACKAGE_PIN R11 [get_ports {io_gpioController[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[11]}]
set_property PACKAGE_PIN H5  [get_ports {io_gpioController[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[12]}]
set_property PACKAGE_PIN H4  [get_ports {io_gpioController[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[13]}]
set_property PACKAGE_PIN H12 [get_ports {io_gpioController[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[14]}]
set_property PACKAGE_PIN H13 [get_ports {io_gpioController[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[15]}]
set_property PACKAGE_PIN F14 [get_ports {io_gpioController[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[16]}]
set_property PACKAGE_PIN G14 [get_ports {io_gpioController[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[17]}]
set_property PACKAGE_PIN J15 [get_ports {io_gpioController[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[18]}]
set_property PACKAGE_PIN J16 [get_ports {io_gpioController[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[19]}]
set_property PACKAGE_PIN P5  [get_ports {io_gpioController[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[20]}]
set_property PACKAGE_PIN P6  [get_ports {io_gpioController[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[21]}]
set_property PACKAGE_PIN H16 [get_ports {io_gpioController[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[22]}]
set_property PACKAGE_PIN G16 [get_ports {io_gpioController[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_gpioController[23]}]

## VGA
set_property PACKAGE_PIN T9  [get_ports {io_vga0_hSync}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_hSync}]
set_property PACKAGE_PIN T10 [get_ports {io_vga0_vSync}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_vSync}]
set_property PACKAGE_PIN N16 [get_ports {io_vga0_enable}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_enable}]

set_property PACKAGE_PIN K3  [get_ports {io_vga0_pixels_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_r[0]}]
set_property PACKAGE_PIN K2  [get_ports {io_vga0_pixels_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_r[1]}]
set_property PACKAGE_PIN R5  [get_ports {io_vga0_pixels_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_r[2]}]
set_property PACKAGE_PIN T5  [get_ports {io_vga0_pixels_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_r[3]}]
set_property PACKAGE_PIN P4  [get_ports {io_vga0_pixels_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_g[0]}]
set_property PACKAGE_PIN P3  [get_ports {io_vga0_pixels_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_g[1]}]
set_property PACKAGE_PIN P10 [get_ports {io_vga0_pixels_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_g[2]}]
set_property PACKAGE_PIN P11 [get_ports {io_vga0_pixels_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_g[3]}]
set_property PACKAGE_PIN R6  [get_ports {io_vga0_pixels_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_b[0]}]
set_property PACKAGE_PIN R7  [get_ports {io_vga0_pixels_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_b[1]}]
set_property PACKAGE_PIN H11 [get_ports {io_vga0_pixels_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_b[2]}]
set_property PACKAGE_PIN G12 [get_ports {io_vga0_pixels_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_vga0_pixels_b[3]}]

## I2C
set_property PACKAGE_PIN G15 [get_ports {io_i2c0_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_i2c0_scl}]
set_property PACKAGE_PIN H14 [get_ports {io_i2c0_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_i2c0_sda}]
